### PR TITLE
small readme fixes

### PR DESCRIPTION
**Pull request by Nowosad**

### CODE REVIEW

**Comment by Nowosad** [comment]
BTW @mtennekes - I hope that my "close" issue comments are useful. I've got some spare time and decided to take a look at the tmap's issues and clean them a little bit.

**Comment by mtennekes** [comment]
Yes, definitely! There are still some nice suggestions among the issues, which we also could label as enhancement (if not done already).

**Comment by Nowosad** [comment]
I could do that this afternoon, but I need some permission to do it.

**Comment by mtennekes** [comment]
There you go:-)

**Pull request merged**
