### PR TITLE
adds possibility of selecting other graphic devices

### PR DESCRIPTION
**Pull request by Nowosad**
Related to https://github.com/mtennekes/tmap/issues/585.
Still WIP - I plan to complete it tomorrow.

@mtennekes Do you have any tests/sandboxes for checking if everything is ok with my changes?

### CODE REVIEW

**Comment by mtennekes** [comment]
Thanks! 

The testing routine of tmap cannot be any worse: there are no tests except for the examples in the documentation.

**Comment by Nowosad** [comment]
Ok - it seems to be ok for your review, @mtennekes - https://github.com/mtennekes/tmap/issues/585#issuecomment-897409941

**Comment by mtennekes** [comment]
Great! It works fine. When I made this typo:

```r
tmap_save(m, "choropleth.pdf", device = "cairo_pdf", height = 7) # height interpreted in inches
```

 (`cairo_pdf` should be unquoted) I got this not-helpful error message: 

```r
# Error in dev(filename = filename, width = width, height = height, ...) : 
#  could not find function "dev"
```

**Comment by Nowosad** [comment]
👍🏻 

It should be better now:

``` r
library(tmap)
data("World")
tm = qtm(World)
tmap_save(tm, "choropleth.pdf", device = "cairo_pdf", height = 7)
#> Error: "cairo_pdf" graphic device does not exist
```

<sup>Created on 2021-08-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Let me know if you have better idea about the error message content.

**Pull request merged**
